title: Office 365, SharePoint 2013,Online REST API CRUD Example | Anomepani
description: SharePoint 2013, 2019, Online REST API, Batch API, Office 365, SharePoint List, Library, Site Pages REST API Sample Code, SharePoint Batch API Example  
google_analytics: UA-144636918-1
