title: Sharepoint REST API Tips
description: SharePoint Online|2013|2019, REST API, Batch API, Office 365, SharePoint List|Library, SharePoint CRUD REST/Batch API Sample Code|Example  
google_analytics: UA-144636918-1
